# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        PokedexBundle\Entity\Usuario:
            algorithm: md5
            iterations: 0
            encode_as_base64: false


    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    
    
    providers:
        db_provider:
            entity:
                class: PokedexBundle\Entity\Usuario
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: db_provider
            anonymous: ~
            form_login:
                login_path: index
                check_path: login
                default_target_path: index
            logout: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/regioes, role: ROLE_ADMIN }
        - { path: ^/tipos, role: ROLE_ADMIN }
        - { path: ^/pokemons, role: ROLE_USER }
        - { path: ^/usuarios, role: ROLE_ADMIN }
        - { path: ^/agenda, role: ROLE_USER }
